version: '2'

services:
   db:
     build: ./mysql
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
   php:
    image: nanoninja/php-fpm:7.1
    ports:
      - '8000:80'
    restart: always
    volumes:
       - ./log/apache2/error.log:/var/log/apache2/error.log
       - ./log/apache2/access.log:/var/log/apache2/access.log
       - ./html:/var/www/html
    depends_on:
      - db
volumes:
    db_data:
